version: '3'

networks:
services:
  taskify-1:
    build:
      context: contextPath
      dockerfile: Dockerfile
    
    environment:
      - name=value

    ports:
      -"8001:8001"
    
  taskify-2:
    build:
      context: contextPath
      dockerfile: Dockerfile
    
    environment:
      - name=value

    ports:
      -"8001:8001"
      